language: objective-c 

osx_image: xcode9.2	

before_script:
  - chmod +x scripts/travis/add-key.sh
  - chmod +x scripts/travis/remove-key.sh
  - chmod +x scripts/travis/testflight.sh

notifications:
  on_success: never 
  on_failure: always
  
branches:
  only:
    - master

env:
  global:
    - PROJECT=Snake.xcodeproj
    - PROFILE_NAME=lukebae

matrix:
  include:
    - env: DEST="platform=iOS Simulator,name=iPhone SE" SCHEME="Snake" SDK="iphonesimulator" ACTION="build"
    - env: DEST="platform=iOS Simulator,name=iPhone SE" SCHEME="SnakeUITests" SDK="iphonesimulator" ACTION="test"
    
script:
  - set -o pipefail
  - xcodebuild "$ACTION" -sdk "$SDK" -destination "$DEST" -project "$PROJECT" -scheme "$SCHEME" CODE_SIGNING_REQUIRED=NO
  
after_success:
  - ./scripts/travis/testflight.sh

after_script:
  - ./scripts/travis/remove-key.sh
