# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcversion(version: "9.2")

platform :ios do
  desc "Upload App"
  lane :beta do
    increment_build_number
    increment_version_number
    upload_to_testflight(
                        ipa: "/Users/travis/build/akshaysud/SnakeClassic/IPA/Snake.ipa",
                        skip_submission: true
                        )
  end
end
