# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Buid App"
  lane :beta do
    sync_code_signing(type: "appstore")  
    increment_build_number(build_number: Time.now.getutc.to_i)
    build_app(scheme: "Snake")
    upload_to_testflight
  end
  
  desc "Release"
  lane :release do
  if is_ci
  create_keychain(
    name: "CI",
    password: ENV["MATCH_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  match(
    type: "appstore",
    keychain_name: "CI",
    keychain_password: ENV["MATCH_PASSWORD"],
    readonly: true
  )
else
  match(type: "appstore")
    end
 end
