# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload App"
  lane :beta do
   upload_to_testflight(
     username: "l_tehira@hotmail.com",
     password: "MjPW7RyAyCId9afVNIGZaGCW6xwtnXWtnZlGiKmWrjxj7VKaND9W5Hsfw8r8CrO3MHiKH9OveDO/s7jf9lJt9FqMv5DBgY/AVFXqhTGKDhfFjPYwb4is2kHwzSaQCTo4/QF4jaACWmSd5TUfd0m++NfD9z9oeqGDl/mOIjhOsSrRaqObP28Iq31a0nBMs3yEdTN+g9eX1e4NEayt4+Kq6ycgtqVWze4B/YHweBVf0gx+tqxskx/XUaP/DQ22+1hwj34g270/vUAgC++QB6M3udSaHfC+pXkVqfHoXWFwg7S6BC6yzCTZ1p5KkLlZQSxYeotreVWF/GifuXlAxXLgqWr5XpcztwGlGyNktaZbeca7tF9EZ+Mecy9UJZ9Ehd9LvALdt6rpaWJFYSiJlkuYib9OLFvN1tyOuEUnI9xgQRcaxXGbk/QMZ6ItNOes+rVS5w8/5HnodFc7VwKNI0uRrSZ0NaQyT2ZL81TGjaHsGpsHwMobzXraUSyww0o3Hjmk5y5JRxCt0EDYZCB8zTFhvYd2oOIHehQEjNs8Ypm+JNmgLfRQ+c4P5VqENop1J2kx5RUlhuMH/faaBNFTPEpgGcNCBigFMdsmaR5yPuTAqPUtjndjxXCADhLlH4QOdgJWv41OYWyYPuVaCD5FDEGWyHlJrXr+Gql2JGuqnx2GHj8="
     )
  end
end
